// Netrek wire protocol constants. Source of truth:
// reference_repos/netrek-server/include/packets.h
export const SOCKVERSION = 4;
export const UDPVERSION = 10;
export const SHORTVERSION = 19;

export const SP = {
  MESSAGE: 1,
  PLAYER_INFO: 2,
  KILLS: 3,
  PLAYER: 4,
  TORP_INFO: 5,
  TORP: 6,
  PHASER: 7,
  PLASMA_INFO: 8,
  PLASMA: 9,
  WARNING: 10,
  MOTD: 11,
  YOU: 12,
  QUEUE: 13,
  STATUS: 14,
  PLANET: 15,
  PICKOK: 16,
  LOGIN: 17,
  FLAGS: 18,
  MASK: 19,
  PSTATUS: 20,
  BADVERSION: 21,
  HOSTILE: 22,
  STATS: 23,
  PL_LOGIN: 24,
  RESERVED: 25,
  PLANET_LOC: 26,
  SCAN: 27,
  UDP_REPLY: 28,
  SEQUENCE: 29,
  SC_SEQUENCE: 30,
  RSA_KEY: 31,
  MOTD_PIC: 32,
  STATS2: 33,
  STATUS2: 34,
  PLANET2: 35,
  NEW_MOTD: 36,
  THINGY: 37,
  THINGY_INFO: 38,
  SHIP_CAP: 39,
  PING: 46,
  FEATURE: 60,
} as const;

export const CP = {
  MESSAGE: 1,
  SPEED: 2,
  DIRECTION: 3,
  PHASER: 4,
  PLASMA: 5,
  TORP: 6,
  QUIT: 7,
  LOGIN: 8,
  OUTFIT: 9,
  WAR: 10,
  PRACTR: 11,
  SHIELD: 12,
  REPAIR: 13,
  ORBIT: 14,
  PLANLOCK: 15,
  PLAYLOCK: 16,
  BOMB: 17,
  BEAM: 18,
  CLOAK: 19,
  DET_TORPS: 20,
  DET_MYTORP: 21,
  COPILOT: 22,
  REFIT: 23,
  TRACTOR: 24,
  REPRESS: 25,
  COUP: 26,
  SOCKET: 27,
  OPTIONS: 28,
  BYE: 29,
  DOCKPERM: 30,
  UPDATES: 31,
  RESETSTATS: 32,
  RESERVED: 33,
  SCAN: 34,
  UDP_REQ: 35,
  SEQUENCE: 36,
  RSA_KEY: 37,
  PLANET: 38,
  PING_RESPONSE: 42,
  S_REQ: 43,
  S_THRS: 44,
  S_MESSAGE: 45,
  FEATURE: 60,
} as const;

// Teams (bitmask), ships, player status — struct.h / defs.h
export const TEAM = { IND: 0, FED: 1, ROM: 2, KLI: 4, ORI: 8 } as const;
export const SHIP = {
  SC: 0,
  DD: 1,
  CA: 2,
  BB: 3,
  AS: 4,
  SB: 5,
  ATT: 6,
} as const;
export const PSTATUS = {
  FREE: 0,
  OUTFIT: 1,
  ALIVE: 2,
  EXPLODE: 3,
  DEAD: 4,
  OBSERVE: 5,
} as const;
